# Generated by Django 3.2.4 on 2021-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
