# Generated by Django 3.2.4 on 2021-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disease', '0002_solution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
